apiVersion: v1
kind: Secret
metadata:
  name: cred-provider-config
  namespace: {{.namespace}}
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
data:
  config: {{.credProviderConfigBytes}}
type: Opaque